#!/bin/bash
# kcontext
# By Tedezed

function get_kube_clusters () {
	cont=0
	cluster_found=0
	for cluster in $(kubectl config get-contexts | grep -v NAME | awk '{ print $2 }'); do
		if [ "$1" == "get_clusters" ]; then
			echo "[$cont] $cluster";
		fi
		if [ "$1" == "connect_to_clusters" ] && [ "$2" == "$cont" ]; then
			cluster_type=$(echo "${cluster}" | cut -d '_' -f1)
			cluster_project=$(echo "${cluster}" | cut -d '_' -f2)
			cluster_location=$(echo "${cluster}" | cut -d '_' -f3)
			cluster_location_type=$(echo "${cluster_location}" | grep -o "-" | wc -l)
			cluster_shot_name=$(echo "${cluster}" | cut -d '_' -f4)
			if [ "${cluster_type}" == "gke" ]; then
				if [ "${cluster_location_type}" == "2" ]; then
					cluster_location_command="--zone ${cluster_location}"
				else
					cluster_location_command="--region ${cluster_location}"
				fi
				echo "> gcloud container clusters get-credentials ${cluster_shot_name} ${cluster_location_command} --project ${cluster_project}"
				gcloud container clusters get-credentials ${cluster_shot_name} ${cluster_location_command} --project ${cluster_project}
			fi
			kubectl config use-context $cluster
			cluster_found=1
		fi
		cont=$(( cont + 1 ))
	done
	if [ "$1" == "connect_to_clusters" ] && [ "$cluster_found" == "0" ]; then
		echo "[ERROR] Kubernetes cluster not found"
	fi
}

echo "Current: $(kubectl config current-context)"
echo ""
echo "List of contexts:"
get_kube_clusters "get_clusters"
echo ""
read -r -p 'Context number to switch: ' num_cluster
get_kube_clusters "connect_to_clusters" $num_cluster